### ISSUE TITLE
get the dataset

### ISSUE THREAD

**Issue by Meredith98** [sadvaseb/Machine-Learning-and-Deep-Learning-for-Car-Following#1]

**Comment by sadvaseb** [comment]
Hi @meredith98,
I'd be happy to help you. Unfortunately, I do not have the ownership of Reconstructed NGSIM dataset to share it. I recommend contact directly to the data owners (marcello.montanino@unina.it, vinpunzo@unina.it). They will help you to get the original dataset. When you got the dataset, you should use my code [here](https://github.com/sadvaseb/Restructured-NGSIM-Dataset-for-surrounding-vehicles) to generate my dataset. Then, run the deep learning model.
Please let me know if you need further information.

**Comment by Meredith98** [comment]
Thank you for your help！




Meredith_Ding
***@***.***




------------------ Original ------------------
From: Saeed Vasebi ***@***.***&gt;
Date: Wed,May 19,2021 10:45 AM
To: sadvaseb/Machine-Learning-and-Deep-Learning-for-Car-Following ***@***.***&gt;
Cc: Meredith98 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [sadvaseb/Machine-Learning-and-Deep-Learning-for-Car-Following] get the dataset (#1)





 
Hi,
 I'd be happy to help you. Unfortunately, I do not have the ownership of Reconstructed NGSIM dataset to share it. I recommend contact directly to the data owners ***@***.***, ***@***.***). They will help you to get the original dataset. When you got the dataset, you should use my code here to generate my dataset. Then, run the deep learning model.
 Please let me know if you need further information.
